sudo: false
language: node_js
node_js:
- 'node'
- '8'

cache:
    directories:
    - node_modules # NPM packages

# command to install dependencies
install: npm install

# command to run tests
script :  npm test && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
