sudo: false
language: node_js
node_js:
- 'node'
- '6'

cache:
    directories:
    - node_modules # NPM packages

# command to install dependencies
install: npm install

# command to run tests
script: npm test
